import 'package:car_service_mobile/shared/widgets/banner_carousel_widget.dart';
import 'package:car_service_mobile/shared/widgets/banner_list_widget.dart';

class DataBase {
  List<ItemBannerCarouselWidget> saleList = [
    ItemBannerCarouselWidget(
      title: 'Eco Clean',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-eco-clean.png',
      description: 'Lavagem ecologica',
      sale: 'Em domicílio',
      stars: '4,7',
      ratings: '535',
    ),
    ItemBannerCarouselWidget(
      title: 'Lumar Elétrica',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/flutter_dev.png',
      description: 'Auto Elétrica',
      sale: '30% OFF',
      stars: '4,6',
      ratings: '235',
    ),
    ItemBannerCarouselWidget(
      title: 'Floresta Funilaria e Pintura',
      subtitle: '1.5 km Av Queiróz Filho, 265, 09111-110, Santo André',
      assetImage: 'assets/images/fun-floresta.png',
      description: 'Funilaria e Pintura',
      sale: '15% OFF',
      stars: '4,7',
      ratings: '1235',
    ),
    ItemBannerCarouselWidget(
      title: 'Bosh',
      subtitle: '3.9 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-bosh.png',
      description: 'Car Certer Services',
      stars: '4,9',
      ratings: '835',
    ),
  ];
  List<ItemBannerCarouselWidget> recomendedList = [
    ItemBannerCarouselWidget(
      title: 'Mecânica PV Car',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-pv-car.png',
      description: 'Mecânica especializada',
      sale: '',
      stars: '4,4',
      ratings: '635',
    ),
    ItemBannerCarouselWidget(
      title: 'Top Class',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-top-class.png',
      description: 'Lava Rápido',
      sale: '30% OFF',
      stars: '4,6',
      ratings: '235',
    ),
    ItemBannerCarouselWidget(
      title: 'Gilmar Lub',
      subtitle: '1.5 km Av Queiróz Filho, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-gilmar-lub.png',
      description: 'Troca de Óleo',
      sale: '15% OFF',
      stars: '4,7',
      ratings: '135',
    ),
    ItemBannerCarouselWidget(
      title: 'Uni Peças',
      subtitle: '3.9 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-unipecas.png',
      description: 'Auto Peças',
      stars: '4,9',
      ratings: '35',
    ),
  ];
  List<ItemBannerCarouselWidget> openedList = [
    ItemBannerCarouselWidget(
      title: 'Gilmar Lub',
      subtitle: '1.5 km Av Queiróz Filho, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-gilmar-lub.png',
      description: 'Troca de Óleo',
      sale: '15% OFF',
      stars: '4,7',
      ratings: '135',
    ),
    ItemBannerCarouselWidget(
      title: 'Uni Peças',
      subtitle: '3.9 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-unipecas.png',
      description: 'Auto Peças',
      stars: '4,9',
      ratings: '35',
    ),
    ItemBannerCarouselWidget(
      title: 'Top Class',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-top-class.png',
      description: 'Lava Rápido',
      sale: '30% OFF',
      stars: '4,6',
      ratings: '235',
    ),
  ];

  // -----------------------------------
  List<ItemBannerListWidget> listBanner = [
    ItemBannerListWidget(
      title: 'Eco Clean',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/home.jpg',
      description: 'Lavagem ecologica',
      sale: 'Em domicílio',
      stars: '4,7',
      ratings: '535',
    ),
    ItemBannerListWidget(
      title: 'Lumar Elétrica',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/flutter_dev.png',
      description: 'Auto Elétrica',
      sale: '30% OFF',
      stars: '4,6',
      ratings: '235',
    ),
    ItemBannerListWidget(
      title: 'Floresta Funilaria e Pintura',
      subtitle: '1.5 km Av Queiróz Filho, 265, 09111-110, Santo André',
      assetImage: 'assets/images/home.jpg',
      description: 'Funilaria e Pintura',
      sale: '15% OFF',
      stars: '4,7',
      ratings: '1235',
    ),
    ItemBannerListWidget(
      title: 'Bosh',
      subtitle: '3.9 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/home.jpg',
      description: 'Car Certer Services',
      stars: '4,9',
      ratings: '835',
    ),
  ];

  // LAVAGEM
  List<ItemBannerListWidget> listBannerLava = [
    ItemBannerListWidget(
      title: 'Eco Clean',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-eco-clean.png',
      description: 'Lavagem ecologica',
      sale: 'Em domicílio',
      stars: '4,7',
      ratings: '535',
    ),
    ItemBannerListWidget(
      title: 'Top Class',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-top-class.png',
      description: 'Lava Rápido',
      sale: '30% OFF',
      stars: '4,6',
      ratings: '235',
    ),
    ItemBannerListWidget(
      title: 'Mix Clean',
      subtitle: '1.5 km Av Queiróz Filho, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-mix-clean.png',
      description: 'Lavagem',
      sale: '25% OFF',
      stars: '4,3',
      ratings: '35',
    ),
    ItemBannerListWidget(
      title: 'Lava Rápido Humaitá',
      subtitle: '3.9 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-humaita.png',
      description: 'Lavagem',
      stars: '4,9',
      ratings: '623',
    ),
    ItemBannerListWidget(
      title: 'Flex Clean',
      subtitle: '3.9 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-flex-clean.png',
      description: 'Lavagem',
      stars: '4,5',
      ratings: '53',
    ),
  ];

  List<ItemBannerCarouselWidget> recomendedListLavagem = [
    ItemBannerCarouselWidget(
      title: 'Eco Clean',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-eco-clean.png',
      description: 'Lavagem ecologica',
      sale: 'Em domicílio',
      stars: '4,7',
      ratings: '535',
    ),
    ItemBannerCarouselWidget(
      title: 'Top Class',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-top-class.png',
      description: 'Lava Rápido',
      sale: '30% OFF',
      stars: '4,6',
      ratings: '235',
    ),
  ];

  // OLEO
  List<ItemBannerListWidget> listBannerOleo = [
    ItemBannerListWidget(
      title: 'TFC Lub',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-tfc-lub.png',
      description: 'Troca de Óleo',
      sale: 'Em domicílio',
      stars: '4,7',
      ratings: '535',
    ),
    ItemBannerListWidget(
      title: 'Tropical Lub',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-tropical-lub.png',
      description: 'Troca de Óleo',
      sale: 'Em domicílio',
      stars: '4,9',
      ratings: '1535',
    ),
    ItemBannerListWidget(
      title: 'Tec Stop',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-tec-stop.png',
      description: 'Troca de Óleo',
      sale: '',
      stars: '4,2',
      ratings: '285',
    ),
    ItemBannerListWidget(
      title: 'Gilmar Lub',
      subtitle: '1.5 km Av Queiróz Filho, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-gilmar-lub.png',
      description: 'Troca de Óleo',
      sale: '15% OFF',
      stars: '4,1',
      ratings: '235',
    ),
    ItemBannerListWidget(
      title: 'Rei do Óleo',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-rei-do-oleo.png',
      description: 'Troca de Óleo',
      sale: '20% OFF',
      stars: '4,9',
      ratings: '1235',
    ),
    ItemBannerListWidget(
      title: 'D+ Lub Center',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-dmais-lub-center.png',
      description: 'Troca de Óleo',
      sale: '',
      stars: '4,4',
      ratings: '50',
    ),
  ];

  List<ItemBannerCarouselWidget> recomendedListOleo = [
    ItemBannerCarouselWidget(
      title: 'D+ Lub Center',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-dmais-lub-center.png',
      description: 'Troca de Óleo',
      sale: '',
      stars: '4,4',
      ratings: '50',
    ),
    ItemBannerCarouselWidget(
      title: 'Rei do Óleo',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-rei-do-oleo.png',
      description: 'Troca de Óleo',
      sale: '20% OFF',
      stars: '4,9',
      ratings: '1235',
    ),
  ];
  // MECANICA
  List<ItemBannerListWidget> listBannerMec = [
    ItemBannerListWidget(
      title: 'Uni Peças',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-unipecas.png',
      description: 'Mecânica Auto Peças',
      sale: 'Em domicílio',
      stars: '4,7',
      ratings: '535',
    ),
    ItemBannerListWidget(
      title: 'PV Car',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-pv-car.png',
      description: 'Mecânica',
      sale: 'Em domicílio',
      stars: '4,9',
      ratings: '1535',
    ),
    ItemBannerListWidget(
      title: 'GP Auto Peças',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-gp-autopecas.png',
      description: 'Mecânica Auto Peças',
      sale: '',
      stars: '4,6',
      ratings: '285',
    ),
    ItemBannerListWidget(
      title: 'Mecânica BR',
      subtitle: '1.5 km Av Queiróz Filho, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-br.png',
      description: 'Mecânica',
      sale: '',
      stars: '4,1',
      ratings: '235',
    ),
    ItemBannerListWidget(
      title: 'Bosh',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-bosh.png',
      description: 'Mecânica',
      sale: '20% OFF',
      stars: '4,9',
      ratings: '1235',
    ),
    ItemBannerListWidget(
      title: 'Autêntica',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-autentica.png',
      description: 'Mecânica',
      sale: '',
      stars: '4,7',
      ratings: '50',
    ),
  ];

  List<ItemBannerCarouselWidget> recomendedListMec = [
    ItemBannerCarouselWidget(
      title: 'Autêntica',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-autentica.png',
      description: 'Mecânica Auto Peças',
      sale: '',
      stars: '4,7',
      ratings: '50',
    ),
    ItemBannerCarouselWidget(
      title: 'Bosh',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-bosh.png',
      description: 'Mecânica',
      sale: '20% OFF',
      stars: '4,9',
      ratings: '1235',
    ),
  ];

  // Search
  List<ItemBannerListWidget> listBannerSearch = [
    ItemBannerListWidget(
      title: 'Eco Clean',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-eco-clean.png',
      description: 'Lavagem ecologica',
      sale: 'Em domicílio',
      stars: '4,7',
      ratings: '535',
    ),
    ItemBannerListWidget(
      title: 'Top Class',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-top-class.png',
      description: 'Lava Rápido',
      sale: '30% OFF',
      stars: '4,6',
      ratings: '235',
    ),
    ItemBannerListWidget(
      title: 'Mix Clean',
      subtitle: '1.5 km Av Queiróz Filho, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-mix-clean.png',
      description: 'Lavagem',
      sale: '25% OFF',
      stars: '4,3',
      ratings: '35',
    ),
    ItemBannerListWidget(
      title: 'Lava Rápido Humaitá',
      subtitle: '3.9 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-humaita.png',
      description: 'Lavagem',
      stars: '4,9',
      ratings: '623',
    ),
    ItemBannerListWidget(
      title: 'Flex Clean',
      subtitle: '3.9 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/lava-flex-clean.png',
      description: 'Lavagem',
      stars: '4,5',
      ratings: '53',
    ),
    ItemBannerListWidget(
      title: 'Uni Peças',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-unipecas.png',
      description: 'Mecânica Auto Peças',
      sale: 'Em domicílio',
      stars: '4,7',
      ratings: '535',
    ),
    ItemBannerListWidget(
      title: 'PV Car',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-pv-car.png',
      description: 'Mecânica',
      sale: 'Em domicílio',
      stars: '4,9',
      ratings: '1535',
    ),
    ItemBannerListWidget(
      title: 'GP Auto Peças',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-gp-autopecas.png',
      description: 'Mecânica Auto Peças',
      sale: '',
      stars: '4,6',
      ratings: '285',
    ),
    ItemBannerListWidget(
      title: 'Mecânica BR',
      subtitle: '1.5 km Av Queiróz Filho, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-br.png',
      description: 'Mecânica',
      sale: '',
      stars: '4,1',
      ratings: '235',
    ),
    ItemBannerListWidget(
      title: 'Bosh',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-bosh.png',
      description: 'Mecânica',
      sale: '20% OFF',
      stars: '4,9',
      ratings: '1235',
    ),
    ItemBannerListWidget(
      title: 'Autêntica',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/mec-autentica.png',
      description: 'Mecânica',
      sale: '',
      stars: '4,7',
      ratings: '50',
    ),
    ItemBannerListWidget(
      title: 'TFC Lub',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-tfc-lub.png',
      description: 'Troca de Óleo',
      sale: 'Em domicílio',
      stars: '4,7',
      ratings: '535',
    ),
    ItemBannerListWidget(
      title: 'Tropical Lub',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-tropical-lub.png',
      description: 'Troca de Óleo',
      sale: 'Em domicílio',
      stars: '4,9',
      ratings: '1535',
    ),
    ItemBannerListWidget(
      title: 'Tec Stop',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-tec-stop.png',
      description: 'Troca de Óleo',
      sale: '',
      stars: '4,2',
      ratings: '285',
    ),
    ItemBannerListWidget(
      title: 'Gilmar Lub',
      subtitle: '1.5 km Av Queiróz Filho, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-gilmar-lub.png',
      description: 'Troca de Óleo',
      sale: '15% OFF',
      stars: '4,1',
      ratings: '235',
    ),
    ItemBannerListWidget(
      title: 'Rei do Óleo',
      subtitle: '5.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-rei-do-oleo.png',
      description: 'Troca de Óleo',
      sale: '20% OFF',
      stars: '4,9',
      ratings: '1235',
    ),
    ItemBannerListWidget(
      title: 'D+ Lub Center',
      subtitle: '3.5 km Rua Euclides, 265, 09111-110, Santo André',
      assetImage: 'assets/images/oleo-dmais-lub-center.png',
      description: 'Troca de Óleo',
      sale: '',
      stars: '4,4',
      ratings: '50',
    ),
  ];
}
